### PR TITLE
Gray+Blur Hovering Effects

### PR DESCRIPTION
**Pull request by Spandita-dwivedi**
I have added some very useful Hovering effects for frontend developers.
I hope it helps.

### CODE REVIEW

**Comment by shashank-iter** [comment]
@Spandita-dwivedi kindly add the screenshot of the components you made.

**Comment by Spandita-dwivedi** [comment]
Sure sir !

**Comment by Spandita-dwivedi** [comment]
before1
[Before Hovering]

after1

[After Hovering]

before2

[Before Hovering]

after2

[After Hovering]

**Comment by shashank-iter** [comment]
@Spandita-dwivedi Amazing Work. Thank you for contributing.

**Pull request merged**
