### PR TITLE
Footer section

### PR DESCRIPTION
**Pull request by Shridhar-dev**
PR for issue #18

### CODE REVIEW

**Comment by shashank-iter** [comment]
Kindly follow the contribution guidelines and the screenshot of your work for review. @Shridhar-dev

**Comment by Shridhar-dev** [comment]
Preview Image

**Comment by shashank-iter** [comment]
Looks good @dhiraj512 any suggestions, if not kindly merge.

**Comment by shashank-iter** [comment]
Looks good @dhiraj512 any suggestions, if not kindly merge.

**Pull request merged**
