### PR TITLE
Resources file added having UI elements, element library

### PR DESCRIPTION
**Pull request by Pratikshaekbote**

### CODE REVIEW

**Comment by shashank-iter** [comment]
@Pratikshaekbote kindly add the screenshot of your work for review.

**Comment by Pratikshaekbote** [comment]
Screenshot_20221023-211816_Figma
Screenshot_20221023-211735_Figma

**Comment by Pratikshaekbote** [comment]
Hello, these are some of the samples of the work!

**Comment by shashank-iter** [comment]
thank you for contributing @Pratikshaekbote

**Pull request merged**
