### PR TITLE
contact-form

### PR DESCRIPTION
**Pull request by coder-chahal**

### CODE REVIEW

**Comment by Jyo561Python** [comment]
Screenshot?

**Comment by coder-chahal** [comment]
img1

**Comment by coder-chahal** [comment]
img2

**Comment by coder-chahal** [comment]
img3

**Comment by Jyo561Python** [comment]
@coder-chahal try to improve its design please

**Comment by coder-chahal** [comment]
By mistake i was add screnshot in #32

**Comment by coder-chahal** [comment]
@Jyo561Python can you tell sir, which type of improvement..

**Comment by Jyo561Python** [comment]
> @Jyo561Python can you tell sir, which type of improvement..

it seems very monotonous maybe you can highlight the form part add some florescence

**Comment by coder-chahal** [comment]
ss1

**Comment by coder-chahal** [comment]
@Jyo561Python i have commit changes.
 Merge PR wit hactoberfest level..
if you like this:)

**Pull request merged**
