### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by coder-chahal**
Sir plzz kindly exepted PR

### CODE REVIEW

**Comment by Jyo561Python** [comment]
Please follow the guidelines and add a screenshot of your finished component so that it can be reviewed.

**Comment by Jyo561Python** [comment]
It seems to be very basic design can you try out a little different design

you can take inspiration from dribble or tailwind components, just dont copy them !!

**Comment by coder-chahal** [comment]
sure i'll do!

**Comment by coder-chahal** [comment]
fest

**Comment by coder-chahal** [comment]
Hlo sir, plzz check this..
i know it's not looking good but i try my best.
plzz kindly merge my PR.

**Comment by Jyo561Python** [comment]
@coder-chahal put it inside a folder under Navbar and commit again

**Comment by coder-chahal** [comment]
done @Jyo561Python

**Comment by shashank-iter** [comment]
Okay it will be merged soon @coder-chahal . You can go with the other issue. Thanks for contributing.

**Pull request merged**
