### PR TITLE
added a navbar (issue #114)

### PR DESCRIPTION
**Pull request by saran1522**
As I have assigned issue #114, here is the code file.

### CODE REVIEW

**Comment by Jyo561Python** [comment]
@saran1522 Please add a Screenshot of your component

**Comment by saran1522** [comment]
I have already raised the issue for the same and someone assigned it to me. ScreenShot is added in that issue. Here is the SS-


Screenshot 2022-10-17 191228

**Comment by saran1522** [comment]
Please look at it.

**Comment by shashank-iter** [comment]
@saran1522 Good work. Thank you for contributing.

**Pull request merged**
