### PR TITLE
Added Canvas Component

### PR DESCRIPTION
**Pull request by prankush-tech**

### CODE REVIEW

**Comment by Jyo561Python** [comment]
Please add a screenshot of your component to your repo

**Comment by prankush-tech** [comment]
# This black canvas with 3D distorted cube is a canvas component, ITS screenshot has already been added to repository.
canvas

**Comment by Jyo561Python** [comment]
Is it an animated component?

**Comment by prankush-tech** [comment]
Yes its a re-useable canvas component , we can use that to add 3D impressiveness in any website.

**Pull request merged**
