### PR TITLE
Added Glass morphed Advice Generator

### PR DESCRIPTION
**Pull request by shivjha-2712**

### CODE REVIEW

**Comment by shivjha-2712** [comment]
Have Added Screenshot as well please do let me help with my first PR for this year Hacktoberfest2022

**Comment by shashank-iter** [comment]
@shivjha-2712 Add the screenshot right here in the comment section of the PR please.

**Comment by shashank-iter** [comment]
@shivjha-2712 Add the screenshot right here in the comment section of the PR please.

**Comment by shivjha-2712** [comment]
Screenshot (1349)
 Here is the Screenshot as you requested me to post

**Comment by shashank-iter** [comment]
@shivjha-2712  Looks cool. Merging it.

**Comment by shivjha-2712** [comment]
Thanks

**Pull request merged**
