### PR TITLE
New-Card-Component

### PR DESCRIPTION
**Pull request by hansupadhyay007**
Hey There,

I am adding a new Card Component to your Library.

### CODE REVIEW

**Comment by shashank-iter** [comment]
@hansupadhyay007  Kindly follow the contribution guidelines and send a screenshot of your work for review.

**Comment by hansupadhyay007** [comment]
All the contributions guidelines which has been said has been fulfilled. I have already read the instructions before starting.

**Comment by hansupadhyay007** [comment]
cardpic1
cardpic2

**Comment by shashank-iter** [comment]
@hansupadhyay007 amazing work. Your PR will get merged soon. Thank you for contributing.

**Pull request merged**
