### PR TITLE
REGISTRATION FORM created

### PR DESCRIPTION
**Pull request by Swastik200**
plz confirm
Screenshot (1)

### CODE REVIEW

**Comment by shashank-iter** [comment]
@Swastik200 add the screenshot of the components not the code.

**Comment by Swastik200** [comment]
Can u please explain which components?

**Comment by shashank-iter** [comment]
@Swastik200 you have made a form right ? Kindly upload the screenshot of that form.....like open the html file in your browser, take the screenshot and upload it so we can have a look at it. That's already mentioned in contribution guidelines.

**Comment by Swastik200** [comment]
Ok, will do that.

**Comment by Swastik200** [comment]
plz check
Screenshot (2)

**Comment by shashank-iter** [comment]
Looks great @Swastik200 . We are merging it. Thank you for contributing.

**Comment by Swastik200** [comment]
Thanks a lot.

**Pull request merged**
