### PR TITLE
Added a CSS based UI for Product Card

### PR DESCRIPTION
**Pull request by shivam-jha2712**
It is a zip file and contains all the necessary assets corresponding to the making of the given product card and does contain a gif of the working UI

### CODE REVIEW

**Comment by Jyo561Python** [comment]
Hey Shivam , Thanks for Contributing to this Repo
Amazing Work, Kudos to you

Just a request put all the files in a folder in the repo and name the folder as Product Component

just apply these changes and we will merge your request

**Comment by shivam-jha2712** [comment]
Have added all the data as a folder You could merge it now.

**Comment by shivam-jha2712** [comment]
Have added the folder accordingly please merge it accordingly

**Comment by shivam-jha2712** [comment]
Thanks

**Pull request merged**
