### PR TITLE
Eclipse animation added!

### PR DESCRIPTION
**Pull request by ankita-104**

### CODE REVIEW

**Comment by Jyo561Python** [comment]
Please add a screenshot

**Comment by ankita-104** [comment]
WhatsApp Image 2022-10-07 at 18 07 28

**Comment by ankita-104** [comment]
This is an animation so these 3 images depict the 3 phases in general ^_^

**Comment by ankita-104** [comment]
WhatsApp Image 2022-10-07 at 18 18 47


Here is one more of it

**Pull request merged**
