### PR TITLE
adding login_page2

### PR DESCRIPTION
**Pull request by MangEs23**
Screenshot 2022-10-04 211615
Screenshot 2022-10-04 211913
Screenshot 2022-10-04 212018

### CODE REVIEW

**Comment by Jyo561Python** [comment]
Thanks for contributing to this repository,
Responsiveness is ok, but
Can you design the login page with a better design 

you can take inspiration from dribble and tailwind..!

**Comment by shashank-iter** [comment]
Amazing Design @MangEs23. Really awesome UI. Your PR will be merged shortly. Thank you for contributing. @Jyo561Python kindly merge this PR.

**Comment by MangEs23** [comment]
sorry that I'm not really good on coding, actually I take inspiration from this site https://saweria.co/ but ok I'll try it

**Comment by MangEs23** [comment]
Screenshot 2022-10-05 040900

**Comment by MangEs23** [comment]
how's that I've try my best

**Pull request merged**
