### PR TITLE
Added Hovering card with html and css Grid View

### PR DESCRIPTION
**Pull request by Adam-pw**

### CODE REVIEW

**Comment by Jyo561Python** [comment]
@Adam-pw please add a screenshot of your component

**Comment by Adam-pw** [comment]
Screenshot from 2022-10-22 19-55-20

**Comment by shashank-iter** [comment]
looks great @Adam-pw. Thank you  for contributing.

**Comment by shashank-iter** [comment]
looks great @Adam-pw. Thank you  for contributing.

**Pull request merged**
