### PR TITLE
contact_UI

### PR DESCRIPTION
**Pull request by 18Ayushi**
contact ui
hey!
@shashank-iter i have attached the screenshot of the completed task "conatct UI page" , could you check and merge it.

### CODE REVIEW

**Comment by 18Ayushi** [comment]
added contact UI page

**Comment by shashank-iter** [comment]
@18Ayushi Yup, it looks pretty good. Thanks for contributing. Your PR will be merged soon.

**Comment by shashank-iter** [comment]
@18Ayushi Yup, it looks pretty good. Thanks for contributing. Your PR will be merged soon.

**Comment by Jyo561Python** [comment]
@18Ayushi I have a task if you can implement a dark/light mode to your contact form

**Pull request merged**
